//----------------------------------------
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Lazarus.modifiedLGPL
//----------------------------------------

procedure CefMediaAccessCallback_Cont(); extdecl;
begin
  handleExceptionBegin
  handleExceptionEnd
end;

procedure CefMediaAccessCallback_Cancel(); extdecl;
begin
  handleExceptionBegin
  handleExceptionEnd
end;

exports
  CefMediaAccessCallback_Cont,
  CefMediaAccessCallback_Cancel;