//----------------------------------------
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Lazarus.modifiedLGPL
//----------------------------------------

procedure RunQuickMenuCallback_Cont(); extdecl;
begin
  handleExceptionBegin
  handleExceptionEnd
end;

procedure RunQuickMenuCallback_Cancel(); extdecl;
begin
  handleExceptionBegin
  handleExceptionEnd
end;


exports
  RunQuickMenuCallback_Cont,
  RunQuickMenuCallback_Cancel;