//----------------------------------------
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Lazarus.modifiedLGPL
//----------------------------------------

{====== events ======}
procedure CEFChromium_SetOnCookieVisitorDestroyed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCookieVisitorDestroyed}
  {$DEFINE EventName := OnCookieVisitorDestroyed}
  EventMethodCode
end;

procedure CEFChromium_SetOnCookiesVisited(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCookiesVisited}
  {$DEFINE EventName := OnCookiesVisited}
  EventMethodCode
end;

procedure CEFChromium_SetOnCookiesFlushed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCookiesFlushed}
  {$DEFINE EventName := OnCookiesFlushed}
  EventMethodCode
end;

procedure CEFChromium_SetOnCookiesDeleted(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCookiesDeleted}
  {$DEFINE EventName := OnCookiesDeleted}
  EventMethodCode
end;

procedure CEFChromium_SetOnCookieSet(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCookieSet}
  {$DEFINE EventName := OnCookieSet}
  EventMethodCode
end;

procedure CEFChromium_SetOnAfterCreated(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAfterCreated}
  {$DEFINE EventName := OnAfterCreated}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforeBrowse(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeBrowse}
  {$DEFINE EventName := OnBeforeBrowse}
  EventMethodCode
end;

procedure CEFChromium_SetOnAddressChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAddressChange}
  {$DEFINE EventName := OnAddressChange}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforeClose(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeClose}
  {$DEFINE EventName := OnBeforeClose}
  EventMethodCode
end;

procedure CEFChromium_SetOnClose(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnClose}
  {$DEFINE EventName := OnClose}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforeContextMenu(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeContextMenu}
  {$DEFINE EventName := OnBeforeContextMenu}
  EventMethodCode
end;

procedure CEFChromium_SetOnContextMenuCommand(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnContextMenuCommand}
  {$DEFINE EventName := OnContextMenuCommand}
  EventMethodCode
end;

procedure CEFChromium_SetOnContextMenuDismissed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnContextMenuDismissed}
  {$DEFINE EventName := OnContextMenuDismissed}
  EventMethodCode
end;

procedure CEFChromium_SetOnPdfPrintFinished(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPdfPrintFinished}
  {$DEFINE EventName := OnPdfPrintFinished}
  EventMethodCode
end;

procedure CEFChromium_SetOnLoadStart(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnLoadStart}
  {$DEFINE EventName := OnLoadStart}
  EventMethodCode
end;

procedure CEFChromium_SetOnLoadingStateChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnLoadingStateChange}
  {$DEFINE EventName := OnLoadingStateChange}
  EventMethodCode
end;

procedure CEFChromium_SetOnLoadingProgressChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnLoadingProgressChange}
  {$DEFINE EventName := OnLoadingProgressChange}
  EventMethodCode
end;

procedure CEFChromium_SetOnLoadError(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnLoadError}
  {$DEFINE EventName := OnLoadError}
  EventMethodCode
end;

procedure CEFChromium_SetOnLoadEnd(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnLoadEnd}
  {$DEFINE EventName := OnLoadEnd}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforeDownload(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeDownload}
  {$DEFINE EventName := OnBeforeDownload}
  EventMethodCode
end;

procedure CEFChromium_SetOnDownloadUpdated(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDownloadUpdated}
  {$DEFINE EventName := OnDownloadUpdated}
  EventMethodCode
end;

procedure CEFChromium_SetOnZoomPctAvailable(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnZoomPctAvailable}
  {$DEFINE EventName := OnZoomPctAvailable}
  EventMethodCode
end;

procedure CEFChromium_SetOnFullScreenModeChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFullScreenModeChange}
  {$DEFINE EventName := OnFullScreenModeChange}
  EventMethodCode
end;

procedure CEFChromium_SetOnKeyEvent(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnKeyEvent}
  {$DEFINE EventName := OnKeyEvent}
  EventMethodCode
end;

procedure CEFChromium_SetOnTitleChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTitleChange}
  {$DEFINE EventName := OnTitleChange}
  EventMethodCode
end;

procedure CEFChromium_SetOnRenderCompMsg(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$ifdef windows}
  {$DEFINE EventMethodName := ChromiumEvent_OnRenderCompMsg}
  {$DEFINE EventName := OnRenderCompMsg}
  EventMethodCode
  {$endif}
end;

procedure CEFChromium_SetOnWidgetCompMsg(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$ifdef windows}
  {$DEFINE EventMethodName := ChromiumEvent_OnWidgetCompMsg}
  {$DEFINE EventName := OnWidgetCompMsg}
  EventMethodCode
  {$endif}
end;

procedure CEFChromium_SetOnBrowserCompMsg(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$ifdef windows}
  {$DEFINE EventMethodName := ChromiumEvent_OnBrowserCompMsg}
  {$DEFINE EventName := OnBrowserCompMsg}
  EventMethodCode
  {$endif}
end;

procedure CEFChromium_SetOnRenderProcessTerminated(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRenderProcessTerminated}
  {$DEFINE EventName := OnRenderProcessTerminated}
  EventMethodCode
end;

procedure CEFChromium_SetOnRenderViewReady(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRenderViewReady}
  {$DEFINE EventName := OnRenderViewReady}
  EventMethodCode
end;

procedure CEFChromium_SetOnScrollOffsetChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnScrollOffsetChanged}
  {$DEFINE EventName := OnScrollOffsetChanged}
  EventMethodCode
end;

procedure CEFChromium_SetOnProcessMessageReceived(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnProcessMessageReceived}
  {$DEFINE EventName := OnProcessMessageReceived}
  EventMethodCode
end;

procedure CEFChromium_SetOnFindResult(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFindResult}
  {$DEFINE EventName := OnFindResult}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforeResourceLoad(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeResourceLoad}
  {$DEFINE EventName := OnBeforeResourceLoad}
  EventMethodCode
end;

procedure CEFChromium_SetOnResourceResponse(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnResourceResponse}
  {$DEFINE EventName := OnResourceResponse}
  EventMethodCode
end;

procedure CEFChromium_SetOnResourceRedirect(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnResourceRedirect}
  {$DEFINE EventName := OnResourceRedirect}
  EventMethodCode
end;

procedure CEFChromium_SetOnResourceLoadComplete(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnResourceLoadComplete}
  {$DEFINE EventName := OnResourceLoadComplete}
  EventMethodCode
end;

procedure CEFChromium_SetOnFrameAttached(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFrameAttached}
  {$DEFINE EventName := OnFrameAttached}
  EventMethodCode
end;

procedure CEFChromium_SetOnFrameCreated(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFrameCreated}
  {$DEFINE EventName := OnFrameCreated}
  EventMethodCode
end;

procedure CEFChromium_SetOnFrameDetached(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFrameDetached}
  {$DEFINE EventName := OnFrameDetached}
  EventMethodCode
end;

procedure CEFChromium_SetOnMainFrameChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnMainFrameChanged}
  {$DEFINE EventName := OnMainFrameChanged}
  EventMethodCode
end;

procedure CEFChromium_SetOnBeforePopup(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforePopup}
  {$DEFINE EventName := OnBeforePopup}
  EventMethodCode
end;

procedure CEFChromium_SetOnOpenUrlFromTab(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnOpenUrlFromTab}
  {$DEFINE EventName := OnOpenUrlFromTab}
  EventMethodCode
end;

procedure CEFChromium_SetOnDragEnter(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDragEnter}
  {$DEFINE EventName := OnDragEnter}
  EventMethodCode
end;

procedure CEFChromium_SetOnDraggableRegionsChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDraggableRegionsChanged}
  {$DEFINE EventName := OnDraggableRegionsChanged}
  EventMethodCode
end;

procedure CEFChromium_SetOnGetAuthCredentials(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetAuthCredentials}
  {$DEFINE EventName := OnGetAuthCredentials}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionBeforeBackgroundBrowser(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionBeforeBackgroundBrowser}
  {$DEFINE EventName := OnExtensionBeforeBackgroundBrowser}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionBeforeBrowser(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionBeforeBrowser}
  {$DEFINE EventName := OnExtensionBeforeBrowser}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionCanAccessBrowser(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionCanAccessBrowser}
  {$DEFINE EventName := OnExtensionCanAccessBrowser}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionGetActiveBrowser(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionGetActiveBrowser}
  {$DEFINE EventName := OnExtensionGetActiveBrowser}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionGetExtensionResource(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionGetExtensionResource}
  {$DEFINE EventName := OnExtensionGetExtensionResource}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionLoaded(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionLoaded}
  {$DEFINE EventName := OnExtensionLoaded}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionLoadFailed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionLoadFailed}
  {$DEFINE EventName := OnExtensionLoadFailed}
  EventMethodCode
end;

procedure CEFChromium_SetOnExtensionUnloaded(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExtensionUnloaded}
  {$DEFINE EventName := OnExtensionUnloaded}
  EventMethodCode
end;

procedure CEFChromium_OnAcceleratedPaint(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAcceleratedPaint}
  {$DEFINE EventName := OnAcceleratedPaint}
  EventMethodCode
end;

procedure CEFChromium_OnAllConnectionsClosed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAllConnectionsClosed}
  {$DEFINE EventName := OnAllConnectionsClosed}
  EventMethodCode
end;

procedure CEFChromium_OnAudioStreamError(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAudioStreamError}
  {$DEFINE EventName := OnAudioStreamError}
  EventMethodCode
end;

procedure CEFChromium_OnAudioStreamPacket(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAudioStreamPacket}
  {$DEFINE EventName := OnAudioStreamPacket}
  EventMethodCode
end;

procedure CEFChromium_OnAudioStreamStarted(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAudioStreamStarted}
  {$DEFINE EventName := OnAudioStreamStarted}
  EventMethodCode
end;

procedure CEFChromium_OnAudioStreamStopped(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAudioStreamStopped}
  {$DEFINE EventName := OnAudioStreamStopped}
  EventMethodCode
end;

procedure CEFChromium_OnAutoResize(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnAutoResize}
  {$DEFINE EventName := OnAutoResize}
  EventMethodCode
end;

procedure CEFChromium_OnBeforeUnloadDialog(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnBeforeUnloadDialog}
  {$DEFINE EventName := OnBeforeUnloadDialog}
  EventMethodCode
end;

procedure CEFChromium_OnCanDownload(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCanDownload}
  {$DEFINE EventName := OnCanDownload}
  EventMethodCode
end;

procedure CEFChromium_OnCanSaveCookie(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCanSaveCookie}
  {$DEFINE EventName := OnCanSaveCookie}
  EventMethodCode
end;

procedure CEFChromium_OnCanSendCookie(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCanSendCookie}
  {$DEFINE EventName := OnCanSendCookie}
  EventMethodCode
end;

procedure CEFChromium_OnCertificateError(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCertificateError}
  {$DEFINE EventName := OnCertificateError}
  EventMethodCode
end;

procedure CEFChromium_OnCertificateExceptionsCleared(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCertificateExceptionsCleared}
  {$DEFINE EventName := OnCertificateExceptionsCleared}
  EventMethodCode
end;

procedure CEFChromium_OnChromeCommand(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnChromeCommand}
  {$DEFINE EventName := OnChromeCommand}
  EventMethodCode
end;

procedure CEFChromium_OnConsoleMessage(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnConsoleMessage}
  {$DEFINE EventName := OnConsoleMessage}
  EventMethodCode
end;

procedure CEFChromium_OnCursorChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnCursorChange}
  {$DEFINE EventName := OnCursorChange}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsAgentAttached(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsAgentAttached}
  {$DEFINE EventName := OnDevToolsAgentAttached}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsAgentDetached(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsAgentDetached}
  {$DEFINE EventName := OnDevToolsAgentDetached}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsEvent(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsEvent}
  {$DEFINE EventName := OnDevToolsEvent}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsMessage(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsMessage}
  {$DEFINE EventName := OnDevToolsMessage}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsMethodRawResult(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsMethodRawResult}
  {$DEFINE EventName := OnDevToolsMethodRawResult}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsMethodResult(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsMethodResult}
  {$DEFINE EventName := OnDevToolsMethodResult}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsRawEvent(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsRawEvent}
  {$DEFINE EventName := OnDevToolsRawEvent}
  EventMethodCode
end;

procedure CEFChromium_OnDevToolsRawMessage(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDevToolsRawMessage}
  {$DEFINE EventName := OnDevToolsRawMessage}
  EventMethodCode
end;

procedure CEFChromium_OnDialogClosed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDialogClosed}
  {$DEFINE EventName := OnDialogClosed}
  EventMethodCode
end;

procedure CEFChromium_OnDismissPermissionPrompt(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDismissPermissionPrompt}
  {$DEFINE EventName := OnDismissPermissionPrompt}
  EventMethodCode
end;

procedure CEFChromium_OnDocumentAvailableInMainFrame(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDocumentAvailableInMainFrame}
  {$DEFINE EventName := OnDocumentAvailableInMainFrame}
  EventMethodCode
end;

procedure CEFChromium_OnDownloadImageFinished(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnDownloadImageFinished}
  {$DEFINE EventName := OnDownloadImageFinished}
  EventMethodCode
end;

procedure CEFChromium_OnExecuteTaskOnCefThread(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnExecuteTaskOnCefThread}
  {$DEFINE EventName := OnExecuteTaskOnCefThread}
  EventMethodCode
end;

procedure CEFChromium_OnFavIconUrlChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFavIconUrlChange}
  {$DEFINE EventName := OnFavIconUrlChange}
  EventMethodCode
end;

procedure CEFChromium_OnFileDialog(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnFileDialog}
  {$DEFINE EventName := OnFileDialog}
  EventMethodCode
end;

procedure CEFChromium_OnGetAccessibilityHandler(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetAccessibilityHandler}
  {$DEFINE EventName := OnGetAccessibilityHandler}
  EventMethodCode
end;

procedure CEFChromium_OnGetAudioParameters(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetAudioParameters}
  {$DEFINE EventName := OnGetAudioParameters}
  EventMethodCode
end;

procedure CEFChromium_OnGetResourceHandler(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetResourceHandler}
  {$DEFINE EventName := OnGetResourceHandler}
  EventMethodCode
end;

procedure CEFChromium_OnGetResourceRequestHandler_ReqCtxHdlr(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetResourceRequestHandler_ReqCtxHdlr}
  {$DEFINE EventName := OnGetResourceRequestHandler_ReqCtxHdlr}
  EventMethodCode
end;

procedure CEFChromium_OnGetResourceRequestHandler_ReqHdlr(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetResourceRequestHandler_ReqHdlr}
  {$DEFINE EventName := OnGetResourceRequestHandler_ReqHdlr}
  EventMethodCode
end;

procedure CEFChromium_OnGetResourceResponseFilter(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetResourceResponseFilter}
  {$DEFINE EventName := OnGetResourceResponseFilter}
  EventMethodCode
end;

procedure CEFChromium_OnGetRootScreenRect(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetRootScreenRect}
  {$DEFINE EventName := OnGetRootScreenRect}
  EventMethodCode
end;

procedure CEFChromium_OnGetScreenInfo(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetScreenInfo}
  {$DEFINE EventName := OnGetScreenInfo}
  EventMethodCode
end;

procedure CEFChromium_OnGetScreenPoint(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetScreenPoint}
  {$DEFINE EventName := OnGetScreenPoint}
  EventMethodCode
end;

procedure CEFChromium_OnGetTouchHandleSize(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetTouchHandleSize}
  {$DEFINE EventName := OnGetTouchHandleSize}
  EventMethodCode
end;

procedure CEFChromium_OnGetViewRect(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGetViewRect}
  {$DEFINE EventName := OnGetViewRect}
  EventMethodCode
end;

procedure CEFChromium_OnGotFocus(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnGotFocus}
  {$DEFINE EventName := OnGotFocus}
  EventMethodCode
end;

procedure CEFChromium_OnHttpAuthCredentialsCleared(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnHttpAuthCredentialsCleared}
  {$DEFINE EventName := OnHttpAuthCredentialsCleared}
  EventMethodCode
end;

procedure CEFChromium_OnIMECompositionRangeChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnIMECompositionRangeChanged}
  {$DEFINE EventName := OnIMECompositionRangeChanged}
  EventMethodCode
end;

procedure CEFChromium_OnJsDialog(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnJsDialog}
  {$DEFINE EventName := OnJsDialog}
  EventMethodCode
end;

procedure CEFChromium_OnMediaAccessChange(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnMediaAccessChange}
  {$DEFINE EventName := OnMediaAccessChange}
  EventMethodCode
end;

procedure CEFChromium_OnMediaRouteCreateFinished(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnMediaRouteCreateFinished}
  {$DEFINE EventName := OnMediaRouteCreateFinished}
  EventMethodCode
end;

procedure CEFChromium_OnMediaSinkDeviceInfo(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnMediaSinkDeviceInfo}
  {$DEFINE EventName := OnMediaSinkDeviceInfo}
  EventMethodCode
end;

procedure CEFChromium_OnNavigationVisitorResultAvailable(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnNavigationVisitorResultAvailable}
  {$DEFINE EventName := OnNavigationVisitorResultAvailable}
  EventMethodCode
end;

procedure CEFChromium_OnPaint(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPaint}
  {$DEFINE EventName := OnPaint}
  EventMethodCode
end;

procedure CEFChromium_OnPdfPrintFinished(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPdfPrintFinished}
  {$DEFINE EventName := OnPdfPrintFinished}
  EventMethodCode
end;

procedure CEFChromium_OnPopupShow(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPopupShow}
  {$DEFINE EventName := OnPopupShow}
  EventMethodCode
end;

procedure CEFChromium_OnPopupSize(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPopupSize}
  {$DEFINE EventName := OnPopupSize}
  EventMethodCode
end;

procedure CEFChromium_OnPrefsAvailable(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPrefsAvailable}
  {$DEFINE EventName := OnPrefsAvailable}
  EventMethodCode
end;

procedure CEFChromium_OnPrefsUpdated(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPrefsUpdated}
  {$DEFINE EventName := OnPrefsUpdated}
  EventMethodCode
end;

procedure CEFChromium_OnPreKeyEvent(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnPreKeyEvent}
  {$DEFINE EventName := OnPreKeyEvent}
  EventMethodCode
end;

procedure CEFChromium_OnProtocolExecution(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnProtocolExecution}
  {$DEFINE EventName := OnProtocolExecution}
  EventMethodCode
end;

procedure CEFChromium_OnQuickMenuCommand(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnQuickMenuCommand}
  {$DEFINE EventName := OnQuickMenuCommand}
  EventMethodCode
end;

procedure CEFChromium_OnQuickMenuDismissed(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnQuickMenuDismissed}
  {$DEFINE EventName := OnQuickMenuDismissed}
  EventMethodCode
end;

procedure CEFChromium_OnRenderViewReady(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRenderViewReady}
  {$DEFINE EventName := OnRenderViewReady}
  EventMethodCode
end;

procedure CEFChromium_OnRequestContextInitialized(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRequestContextInitialized}
  {$DEFINE EventName := OnRequestContextInitialized}
  EventMethodCode
end;

procedure CEFChromium_OnRequestMediaAccessPermission(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRequestMediaAccessPermission}
  {$DEFINE EventName := OnRequestMediaAccessPermission}
  EventMethodCode
end;

procedure CEFChromium_OnResetDialogState(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnResetDialogState}
  {$DEFINE EventName := OnResetDialogState}
  EventMethodCode
end;

procedure CEFChromium_OnResolvedHostAvailable(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnResolvedHostAvailable}
  {$DEFINE EventName := OnResolvedHostAvailable}
  EventMethodCode
end;

procedure CEFChromium_OnRouteMessageReceived(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRouteMessageReceived}
  {$DEFINE EventName := OnRouteMessageReceived}
  EventMethodCode
end;

procedure CEFChromium_OnRoutes(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRoutes}
  {$DEFINE EventName := OnRoutes}
  EventMethodCode
end;

procedure CEFChromium_OnRouteStateChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRouteStateChanged}
  {$DEFINE EventName := OnRouteStateChanged}
  EventMethodCode
end;

procedure CEFChromium_OnRunContextMenu(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRunContextMenu}
  {$DEFINE EventName := OnRunContextMenu}
  EventMethodCode
end;

procedure CEFChromium_OnRunQuickMenu(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnRunQuickMenu}
  {$DEFINE EventName := OnRunQuickMenu}
  EventMethodCode
end;

procedure CEFChromium_OnSelectClientCertificate(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnSelectClientCertificate}
  {$DEFINE EventName := OnSelectClientCertificate}
  EventMethodCode
end;

procedure CEFChromium_OnSetFocus(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnSetFocus}
  {$DEFINE EventName := OnSetFocus}
  EventMethodCode
end;

procedure CEFChromium_OnShowPermissionPrompt(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnShowPermissionPrompt}
  {$DEFINE EventName := OnShowPermissionPrompt}
  EventMethodCode
end;

procedure CEFChromium_OnSinks(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnSinks}
  {$DEFINE EventName := OnSinks}
  EventMethodCode
end;

procedure CEFChromium_OnStartDragging(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnStartDragging}
  {$DEFINE EventName := OnStartDragging}
  EventMethodCode
end;

procedure CEFChromium_OnStatusMessage(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnStatusMessage}
  {$DEFINE EventName := OnStatusMessage}
  EventMethodCode
end;

procedure CEFChromium_OnTakeFocus(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTakeFocus}
  {$DEFINE EventName := OnTakeFocus}
  EventMethodCode
end;

procedure CEFChromium_OnTextResultAvailable(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTextResultAvailable}
  {$DEFINE EventName := OnTextResultAvailable}
  EventMethodCode
end;

procedure CEFChromium_OnTextSelectionChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTextSelectionChanged}
  {$DEFINE EventName := OnTextSelectionChanged}
  EventMethodCode
end;

procedure CEFChromium_OnTooltip(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTooltip}
  {$DEFINE EventName := OnTooltip}
  EventMethodCode
end;

procedure CEFChromium_OnTouchHandleStateChanged(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnTouchHandleStateChanged}
  {$DEFINE EventName := OnTouchHandleStateChanged}
  EventMethodCode
end;

procedure CEFChromium_OnUpdateDragCursor(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnUpdateDragCursor}
  {$DEFINE EventName := OnUpdateDragCursor}
  EventMethodCode
end;

procedure CEFChromium_OnVirtualKeyboardRequested(const AObj: TChromium; AEventData: Pointer); extdecl;
begin
  {$DEFINE EventMethodName := ChromiumEvent_OnVirtualKeyboardRequested}
  {$DEFINE EventName := OnVirtualKeyboardRequested}
  EventMethodCode
end;


exports
   CEFChromium_SetOnAfterCreated,
   CEFChromium_SetOnBeforeBrowse,
   CEFChromium_SetOnAddressChange,
   CEFChromium_SetOnBeforeClose,
   CEFChromium_SetOnClose,
   CEFChromium_SetOnPdfPrintFinished,
   CEFChromium_SetOnZoomPctAvailable,
   CEFChromium_SetOnFullScreenModeChange,
   CEFChromium_SetOnKeyEvent,
   CEFChromium_SetOnTitleChange,
   CEFChromium_SetOnBeforeContextMenu,
   CEFChromium_SetOnContextMenuCommand,
   CEFChromium_SetOnContextMenuDismissed,
   CEFChromium_SetOnBeforePopup,
   CEFChromium_SetOnOpenUrlFromTab,
   CEFChromium_SetOnDragEnter,
   CEFChromium_SetOnDraggableRegionsChanged,//drag - css [-webkit-app-region： drag/no-drag]
   CEFChromium_SetOnLoadStart,
   CEFChromium_SetOnLoadingStateChange,
   CEFChromium_SetOnLoadingProgressChange,
   CEFChromium_SetOnLoadError,
   CEFChromium_SetOnLoadEnd,
   CEFChromium_SetOnBeforeDownload,
   CEFChromium_SetOnDownloadUpdated,
   CEFChromium_SetOnRenderCompMsg,
   CEFChromium_SetOnWidgetCompMsg,
   CEFChromium_SetOnBrowserCompMsg,
   CEFChromium_SetOnRenderProcessTerminated,
   CEFChromium_SetOnRenderViewReady,
   CEFChromium_SetOnScrollOffsetChanged,
   CEFChromium_SetOnProcessMessageReceived,
   CEFChromium_SetOnFindResult,
   CEFChromium_SetOnCookieVisitorDestroyed,
   CEFChromium_SetOnCookiesVisited,
   CEFChromium_SetOnCookiesFlushed,
   CEFChromium_SetOnCookiesDeleted,
   CEFChromium_SetOnCookieSet,
   CEFChromium_SetOnBeforeResourceLoad,
   CEFChromium_SetOnResourceResponse,
   CEFChromium_SetOnResourceRedirect,
   CEFChromium_SetOnResourceLoadComplete,
   CEFChromium_SetOnFrameAttached,
   CEFChromium_SetOnFrameCreated,
   CEFChromium_SetOnFrameDetached,
   CEFChromium_SetOnMainFrameChanged,
   CEFChromium_SetOnGetAuthCredentials,
   CEFChromium_OnAcceleratedPaint,
   CEFChromium_OnAllConnectionsClosed,
   CEFChromium_OnAudioStreamError,
   CEFChromium_OnAudioStreamPacket,
   CEFChromium_OnAudioStreamStarted,
   CEFChromium_OnAudioStreamStopped,
   CEFChromium_OnAutoResize,
   CEFChromium_OnBeforeUnloadDialog,
   CEFChromium_OnCanDownload,
   CEFChromium_OnCanSaveCookie,
   CEFChromium_OnCanSendCookie,
   CEFChromium_OnCertificateError,
   CEFChromium_OnCertificateExceptionsCleared,
   CEFChromium_OnChromeCommand,
   CEFChromium_OnConsoleMessage,
   CEFChromium_OnCursorChange,
   CEFChromium_OnDevToolsAgentAttached,
   CEFChromium_OnDevToolsAgentDetached,
   CEFChromium_OnDevToolsEvent,
   CEFChromium_OnDevToolsMessage,
   CEFChromium_OnDevToolsMethodRawResult,
   CEFChromium_OnDevToolsMethodResult,
   CEFChromium_OnDevToolsRawEvent,
   CEFChromium_OnDevToolsRawMessage,
   CEFChromium_OnDialogClosed,
   CEFChromium_OnDismissPermissionPrompt,
   CEFChromium_OnDocumentAvailableInMainFrame,
   CEFChromium_OnDownloadImageFinished,
   CEFChromium_OnExecuteTaskOnCefThread,
   CEFChromium_OnFavIconUrlChange,
   CEFChromium_OnFileDialog,
   CEFChromium_OnGetAccessibilityHandler,
   CEFChromium_OnGetAudioParameters,
   CEFChromium_OnGetResourceHandler,
   CEFChromium_OnGetResourceRequestHandler_ReqCtxHdlr,
   CEFChromium_OnGetResourceRequestHandler_ReqHdlr,
   CEFChromium_OnGetResourceResponseFilter,
   CEFChromium_OnGetRootScreenRect,
   CEFChromium_OnGetScreenInfo,
   CEFChromium_OnGetScreenPoint,
   CEFChromium_OnGetTouchHandleSize,
   CEFChromium_OnGetViewRect,
   CEFChromium_OnGotFocus,
   CEFChromium_OnHttpAuthCredentialsCleared,
   CEFChromium_OnIMECompositionRangeChanged,
   CEFChromium_OnJsDialog,
   CEFChromium_OnMediaAccessChange,
   CEFChromium_OnMediaRouteCreateFinished,
   CEFChromium_OnMediaSinkDeviceInfo,
   CEFChromium_OnNavigationVisitorResultAvailable,
   CEFChromium_OnPaint,
   CEFChromium_OnPdfPrintFinished,
   CEFChromium_OnPopupShow,
   CEFChromium_OnPopupSize,
   CEFChromium_OnPrefsAvailable,
   CEFChromium_OnPrefsUpdated,
   CEFChromium_OnPreKeyEvent,
   CEFChromium_OnProtocolExecution,
   CEFChromium_OnQuickMenuCommand,
   CEFChromium_OnQuickMenuDismissed,
   CEFChromium_OnRenderViewReady,
   CEFChromium_OnRequestContextInitialized,
   CEFChromium_OnRequestMediaAccessPermission,
   CEFChromium_OnResetDialogState,
   CEFChromium_OnResolvedHostAvailable,
   CEFChromium_OnRouteMessageReceived,
   CEFChromium_OnRoutes,
   CEFChromium_OnRouteStateChanged,
   CEFChromium_OnRunContextMenu,
   CEFChromium_OnRunQuickMenu,
   CEFChromium_OnSelectClientCertificate,
   CEFChromium_OnSetFocus,
   CEFChromium_OnShowPermissionPrompt,
   CEFChromium_OnSinks,
   CEFChromium_OnStartDragging,
   CEFChromium_OnStatusMessage,
   CEFChromium_OnTakeFocus,
   CEFChromium_OnTextResultAvailable,
   CEFChromium_OnTextSelectionChanged,
   CEFChromium_OnTooltip,
   CEFChromium_OnTouchHandleStateChanged,
   CEFChromium_OnUpdateDragCursor,
   CEFChromium_OnVirtualKeyboardRequested
;

