//----------------------------------------
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Lazarus.modifiedLGPL
//----------------------------------------

procedure RunQuickMenuCallback_Cont(const TObj: Pointer; commandId: Integer; eventFlags: Cardinal); extdecl;
begin
end;

procedure RunQuickMenuCallback_Cancel(const TObj: Pointer); extdecl;
begin
end;


exports
  RunQuickMenuCallback_Cont,
  RunQuickMenuCallback_Cancel;
