name: build

on:
  push:
    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:
  # macos
  macos-amd-arm64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [macos-12]
        lazarus-versions: [2.2.6]

    steps:
      - uses: actions/checkout@v4

      # 创建构建后的liblcl二进制压缩包存放目录和设置git仓库
      - name: Config liblcl
        run: |
          mkdir liblclbinary
          git config --global --add safe.directory ./
          git fetch
          chmod +x ./shell/add-package.sh

      # Laz 环境
      - name: Lazarus Build Environment
        uses: sxmxta/lazarus@v1.0.15
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}
          with-cache: false

      # 编译 liblcl :default
      - name: Build Branch main for (liblcl.MacOSX64)
        run: |
          # git checkout origin/main
          git branch
          ./shell/add-package.sh
          lazbuild -B --bm="MacOS64(cocoa)" --ws=cocoa "src/liblcl.lpi"
          zip -j liblclbinary/liblcl.MacOSX64.zip $HOME/golcl/liblcl.dylib
          # 编译 liblcl support m1 m2
          lazbuild -B --bm="MacOS64(cocoa)ARM64" --ws=cocoa "src/liblcl.lpi"
          zip -j liblclbinary/liblcl.MacOSARM64.zip $HOME/golcl/liblcl.dylib

      # 编译 liblcl support flash
      - name: Build Branch Flash-89.0.18 for (liblcl-87.MacOSX)
        run: |
          git clean -xdf
          git checkout origin/Flash-89.0.18
          git branch
          ./shell/add-package.sh
          lazbuild -B --bm="MacOS64(cocoa)" --ws=cocoa "src/liblcl.lpi"
          zip -j liblclbinary/liblcl-87.MacOSX.zip $HOME/golcl/liblcl.dylib

      # 版本发布上传liblcl二进制
      - name: Release
        run : |
          ls -al liblclbinary
