name: build

on:
  push:
    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:
  # linux
  linux-amd64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-20.04]
        lazarus-versions: [2.2.6]

    steps:
      - uses: actions/checkout@v4

      # 创建构建后的liblcl二进制压缩包存放目录和设置git仓库
      # 同时构建所有 linux amd64
      - name: Config liblcl
        run: |
          mkdir liblclbinary
          git config --global --add safe.directory ./
          git fetch
          chmod +x ./shell/add-package.sh
          sudo apt-get install libgtk-3-dev

      # Laz 环境
      - name: Lazarus Build Environment
        uses: sxmxta/lazarus@v1.0.14
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}
          with-cache: false

      # 编译 liblcl support Gtk3 :default
      - name: Build Branch main for (liblcl.Linux64)
        run: |
          # git checkout origin/main
          ./shell/add-package.sh
          lazbuild -B --bm=Linux64 --ws=gtk3 "src/liblcl.lpi"
          zip -j liblclbinary/liblcl.Linux64.zip $HOME/golcl/liblcl.so

      # 编译 liblcl support Gtk2
      - name: Build Branch GTK2-106.1.1 for (liblcl.Linux64GTK2)
        run: |
          git checkout origin/GTK2-106.1.1
          ./shell/add-package.sh
          lazbuild -B --bm=Linux64 --ws=gtk2 "src/liblcl.lpi"
          zip -j liblclbinary/liblcl.Linux64GTK2.zip $HOME/golcl/liblcl.so

      # 编译 liblcl support flash
      - name: Build Branch Flash-89.0.18 for (liblcl-87.Linux64)
        run: |
          git checkout origin/Flash-89.0.18
          ./shell/add-package.sh
          lazbuild -B --bm=Linux64 --ws=gtk2 "src/liblcl.lpi"
          zip -j liblclbinary/liblcl-87.Linux64.zip $HOME/golcl/liblcl.so

      # 版本发布上传liblcl二进制
      - name: Release
        run : |
          ls -al liblclbinary
