name: build

on:
  push:
    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:
  # linux
  linux-amd64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-20.04 ]
        lazarus-versions: [ 2.2.6 ]

    steps:
      - uses: actions/checkout@v4

      # 创建构建后的liblcl二进制压缩包存放目录和设置git仓库
      # 同时构建所有 linux amd64
      - name: Config liblcl
        run: |
          mkdir $RUNNER_WORKSPACE/liblclbinary
          git config --global --add safe.directory ./
          git fetch
          chmod +x ./shell/add-package.sh
          sudo apt-get install libgtk-3-dev

      # Laz 环境
      - name: Lazarus Build Environment
        uses: sxmxta/lazarus@v1.0.15
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}
          with-cache: false

      # 编译 liblcl support Gtk3 :default
      - name: Build Branch main for (liblcl.Linux64)
        run: |
          git clean -xdf
          # git checkout origin/main
          ./shell/add-package.sh
          lazbuild -B --bm=Linux64 --ws=gtk3 "src/liblcl.lpi"

