name: build-dev

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:
  # macos
  macos-amd64-arm64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ macOS-12 ]
        lazarus-versions: [ 2.2.6 ]

    steps:
      - uses: actions/checkout@v4

      # 创建构建后的liblcl二进制压缩包存放目录和设置git仓库
      - name: Config liblcl
        run: |
          mkdir $RUNNER_WORKSPACE/liblclbinary
          git config --global --add safe.directory ./
          git fetch
          chmod +x ./shell/add-package.sh

      # Laz 环境
      - name: Lazarus Build Environment
        uses: sxmxta/lazarus@v1.0.17
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}
          with-cache: false

      # 编译 liblcl :default
      - name: Build Branch main for (liblcl.MacOSX64)
        run: |
          git clean -xdf
          # git checkout origin/main
          ./shell/add-package.sh
          lazbuild -B --bm="MacOS64(cocoa)" --ws=cocoa "src/liblcl.lpi"
          zip -j $RUNNER_WORKSPACE/liblclbinary/liblcl.MacOSX64.zip $HOME/golcl/liblcl.dylib

      - name: Build Branch main for (liblcl.MacOS(arm64))
        run: |
          lazbuild -B --bm="MacOS64(cocoa)" --ws=cocoa "src/liblcl.lpi"
          zip -j $RUNNER_WORKSPACE/liblclbinary/liblcl.MacOSX64.zip $HOME/golcl/liblcl.dylib

      # 编译 liblcl support flash
      - name: Build Branch Flash-89.0.18 for (liblcl-87.MacOSX)
        run: |
          git clean -xdf
          git checkout origin/Flash-89.0.18
          ./shell/add-package.sh
          lazbuild -B --bm="MacOS64(cocoa)" --ws=cocoa "src/liblcl.lpi"
          zip -j $RUNNER_WORKSPACE/liblclbinary/liblcl-87.MacOSX.zip $HOME/golcl/liblcl.dylib

      # 编译 liblcl support flash
      - name: Build Branch Flash-89.0.18 for (liblcl-87.MacOS(arm64))
        run: |
          lazbuild -B --bm="MacOS64(cocoa)ARM64" --ws=cocoa "src/liblcl.lpi"
          zip -j $RUNNER_WORKSPACE/liblclbinary/liblcl-87.MacOSARM64.zip $HOME/golcl/liblcl.dylib
