name: build-test

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:

  Build-End-RUN:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Golang Environment # Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

